var chem = new Object();

chem.names = {};
chem.names['hydrogen'] = 'H';
chem.names['helium'] = 'He';
chem.names['lithium'] = 'Li';
chem.names['beryllium'] = 'Be';
chem.names['boron'] = 'B';
chem.names['carbon'] = 'C';
chem.names['nitrogen'] = 'N';
chem.names['oxygen'] = 'O';
chem.names['fluorine'] = 'F';
chem.names['neon'] = 'Ne';
chem.names['sodium'] = 'Na';
chem.names['magnesium'] = 'Mg';
chem.names['aluminum'] = 'Al';
chem.names['silicon'] = 'Si';
chem.names['phosphorus'] = 'P';
chem.names['sulfur'] = 'S';
chem.names['chlorine'] = 'Cl';
chem.names['argon'] = 'Ar';
chem.names['potassium'] = 'K';
chem.names['calcium'] = 'Ca';
chem.names['scandium'] = 'Sc';
chem.names['titanium'] = 'Ti';
chem.names['vanadium'] = 'V';
chem.names['chromium'] = 'Cr';
chem.names['manganese'] = 'Mn';
chem.names['iron'] = 'Fe';
chem.names['cobalt'] = 'Co';
chem.names['nickel'] = 'Ni';
chem.names['copper'] = 'Cu';
chem.names['zinc'] = 'Zn';
chem.names['gallium'] = 'Ga';
chem.names['germanium'] = 'Ge';
chem.names['arsenic'] = 'As';
chem.names['selenium'] = 'Se';
chem.names['bromine'] = 'Br';
chem.names['krypton'] = 'Kr';
chem.names['rubidium'] = 'Rb';
chem.names['strontium'] = 'Sr';
chem.names['yttrium'] = 'Y';
chem.names['zirconium'] = 'Zr';
chem.names['nioblum'] = 'Nb';
chem.names['molybdenum'] = 'Mo';
chem.names['technetium'] = 'Tc';
chem.names['ruthenium'] = 'Ru';
chem.names['rhodium'] = 'Rh';
chem.names['palladium'] = 'Pd';
chem.names['silver'] = 'Ag';
chem.names['cadmium'] = 'Cd';
chem.names['indium'] = 'In';
chem.names['tin'] = 'Sn';
chem.names['antimony'] = 'Sb';
chem.names['tellurium'] = 'Te';
chem.names['iodine'] = 'I';
chem.names['xenon'] = 'Xe';
chem.names['celsium'] = 'Cs';
chem.names['barium'] = 'Ba';
chem.names['lanthanum'] = 'La';
chem.names['cerium'] = 'Ce';
chem.names['praseodymium'] = 'Pr';
chem.names['neodymium'] = 'Nd';
chem.names['promethium'] = 'Pm';
chem.names['samarium'] = 'Sm';
chem.names['europium'] = 'Eu';
chem.names['gadolinium'] = 'Gd';
chem.names['terbium'] = 'Tb';
chem.names['dysprosium'] = 'Dy';
chem.names['holmium'] = 'Ho';
chem.names['erbium'] = 'Er';
chem.names['thulium'] = 'Tm';
chem.names['ytterbium'] = 'Yb';
chem.names['lutetium'] = 'Lu';
chem.names['hafnium'] = 'Hf';
chem.names['tantalum'] = 'Ta';
chem.names['tungsten'] = 'W';
chem.names['rhenium'] = 'Re';
chem.names['osmium'] = 'Os';
chem.names['iridium'] = 'Ir';
chem.names['plantinum'] = 'Pt';
chem.names['gold'] = 'Au';
chem.names['mercury'] = 'Hg';
chem.names['thallium'] = 'Tl';
chem.names['lead'] = 'Pb';
chem.names['bismuth'] = 'Bi';
chem.names['polonium'] = 'Po';
chem.names['astatine'] = 'At';
chem.names['radon'] = 'Rn';
chem.names['francium'] = 'Fr';
chem.names['radium'] = 'Ra';
chem.names['actinium'] = 'Ac';
chem.names['thorium'] = 'Th';
chem.names['protactinium'] = 'Pa';
chem.names['uranium'] = 'U';
chem.names['neptunium'] = 'Np';
chem.names['plutonium'] = 'Pu';
chem.names['americium'] = 'Am';
chem.names['curium'] = 'Cm';
chem.names['berkelium'] = 'Bk';
chem.names['californium'] = 'Cf';
chem.names['einsteinium'] = 'Es';
chem.names['fermium'] = 'Fm';
chem.names['mendelevium'] = 'Md';
chem.names['nobelium'] = 'No';
chem.names['lawrencium'] = 'Lr';
chem.names['rutherfordium'] = 'Rf';
chem.names['dubnium'] = 'Db';
chem.names['seaborgium'] = 'Sg';
chem.names['bohrium'] = 'Bh';
chem.names['hassium'] = 'Hs';
chem.names['meitnerium'] = 'Mt';
chem.names['darmstadtium'] = 'Ds';
chem.names['roentgenium'] = 'Rg';
chem.names['copernicium'] = 'Cn';
chem.names['ununtrium'] = 'Uut';
chem.names['flevium'] = 'Fl';
chem.names['ununpentium'] = 'Uup';
chem.names['livermorium'] = 'Lv';
chem.names['ununseptium'] = 'Uus';
chem.names['ununoctium'] = 'Uuo';

chem.table = {};
chem.table['H']   = {number:1, amu:1.008, type:'Non Metal'};
chem.table['He']  = {number:2, amu:4.003, type:'Noble Gas'};
chem.table['Li']  = {number:3, amu:6.941, type:'Alkali Metal'};
chem.table['Be']  = {number:4, amu:9.012, type:'Alkaline Earth'};
chem.table['B']   = {number:5, amu:10.811, type:'Semi Metal'};
chem.table['C']   = {number:6, amu:12.011, type:'Non Metal'};
chem.table['N']   = {number:7, amu:14.007, type:'Non Metal'};
chem.table['O']   = {number:8, amu:15.999, type:''};
chem.table['F']   = {number:9, amu:18.998, type:''};
chem.table['Ne']  = {number:10, amu:20.180, type:''};
chem.table['Na']  = {number:11, amu:22.990, type:''};
chem.table['Mg']  = {number:12, amu:24.305, type:''};
chem.table['Al']  = {number:13, amu:26.982, type:''};
chem.table['Si']  = {number:14, amu:28.086, type:''};
chem.table['P']   = {number:15, amu:30.974, type:''};
chem.table['S']   = {number:16, amu:32.066, type:''};
chem.table['Cl']  = {number:17, amu:35.453, type:''};
chem.table['Ar']  = {number:18, amu:39.948, type:''};
chem.table['K']   = {number:19, amu:39.0983, type:''};
chem.table['Ca']  = {number:20, amu:40.078, type:''};
chem.table['Sc']  = {number:21, amu:44.955, type:''};
chem.table['Ti']  = {number:22, amu:47.867, type:''};
chem.table['V']   = {number:23, amu:50.9415, type:''};
chem.table['Cr']  = {number:24, amu:51.9961, type:''};
chem.table['Mn']  = {number:25, amu:54.938, type:''};
chem.table['Fe']  = {number:26, amu:55.845, type:''};
chem.table['Co']  = {number:27, amu:58.933, type:''};
chem.table['Ni']  = {number:28, amu:58.6934, type:''};
chem.table['Cu']  = {number:29, amu:63.546, type:''};
chem.table['Zn']  = {number:30, amu:65.38, type:''};
chem.table['Ga']  = {number:31, amu:69.723, type:''};
chem.table['Ge']  = {number:32, amu:72.63, type:''};
chem.table['As']  = {number:33, amu:74.921, type:''};
chem.table['Se']  = {number:34, amu:78.971, type:''};
chem.table['Br']  = {number:35, amu:79.904, type:''};
chem.table['Kr']  = {number:36, amu:83.798, type:''};
chem.table['Rb']  = {number:37, amu:85.4678, type:''};
chem.table['Sr']  = {number:38, amu:87.62, type:''};
chem.table['Y']   = {number:39, amu:88.90584, type:''};
chem.table['Zr']  = {number:40, amu:91.224, type:''};
chem.table['Nb']  = {number:41, amu:92.90637, type:''};
chem.table['Mo']  = {number:42, amu:95.95, type:''};
chem.table['Tc']  = {number:43, amu:98, type:''};
chem.table['Ru']  = {number:44, amu:101.07, type:''};
chem.table['Rh']  = {number:45, amu:102.9, type:''};
chem.table['Pd']  = {number:46, amu:106.42, type:''};
chem.table['Ag']  = {number:47, amu:107.8682, type:''};
chem.table['Cd']  = {number:48, amu:112.414, type:''};
chem.table['In']  = {number:49, amu:114.818, type:''};
chem.table['Sn']  = {number:50, amu:118.71, type:''};
chem.table['Sb']  = {number:51, amu:121.76, type:''};
chem.table['Te']  = {number:52, amu:127.6, type:''};
chem.table['I']   = {number:53, amu:126.9, type:''};
chem.table['Xe']  = {number:54, amu:131.293, type:''};
chem.table['Cs']  = {number:55, amu:132.9, type:''};
chem.table['Ba']  = {number:56, amu:137.327, type:''};
chem.table['La']  = {number:57, amu:138.9, type:''};
chem.table['Ce']  = {number:58, amu:140.116, type:''};
chem.table['Pr']  = {number:59, amu:140.9, type:''};
chem.table['Nd']  = {number:60, amu:144.242, type:''};
chem.table['Pm']  = {number:61, amu:145, type:''};
chem.table['Sm']  = {number:62, amu:150.36, type:''};
chem.table['Eu']  = {number:63, amu:151.964, type:''};
chem.table['Gd']  = {number:64, amu:157.25, type:''};
chem.table['Tb']  = {number:65, amu:158.92, type:''};
chem.table['Dy']  = {number:66, amu:162.5, type:''};
chem.table['Ho']  = {number:67, amu:164.93, type:''};
chem.table['Er']  = {number:68, amu:167.259, type:''};
chem.table['Tm']  = {number:69, amu:168.93, type:''};
chem.table['Yb']  = {number:70, amu:173.054, type:''};
chem.table['Lu']  = {number:71, amu:174.9668, type:''};
chem.table['Hf']  = {number:72, amu:178.49, type:''};
chem.table['Ta']  = {number:73, amu:180.94, type:''};
chem.table['W']   = {number:74, amu:183.84, type:''};
chem.table['Re']  = {number:75, amu:186.207, type:''};
chem.table['Os']  = {number:76, amu:190.23, type:''};
chem.table['Ir']  = {number:77, amu:192.217, type:''};
chem.table['Pt']  = {number:78, amu:195.084, type:''};
chem.table['Au']  = {number:79, amu:196.96, type:''};
chem.table['Hg']  = {number:80, amu:200.59, type:''};
chem.table['Tl']  = {number:81, amu:204.38, type:''};
chem.table['Pb']  = {number:82, amu:207.2, type:''};
chem.table['Bi']  = {number:83, amu:208.98, type:''};
chem.table['Po']  = {number:84, amu:209, type:''};
chem.table['At']  = {number:85, amu:210, type:''};
chem.table['Rn']  = {number:86, amu:222, type:''};
chem.table['Fr']  = {number:87, amu:223, type:''};
chem.table['Ra']  = {number:88, amu:226, type:''};
chem.table['Ac']  = {number:89, amu:227, type:''};
chem.table['Th']  = {number:90, amu:232.0377, type:''};
chem.table['Pa']  = {number:91, amu:231.03, type:''};
chem.table['U']   = {number:92, amu:238.02, type:''};
chem.table['Np']  = {number:93, amu:237, type:''};
chem.table['Pu']  = {number:94, amu:244, type:''};
chem.table['Am']  = {number:95, amu:243, type:''};
chem.table['Cm']  = {number:96, amu:247, type:''};
chem.table['Bk']  = {number:97, amu:247, type:''};
chem.table['Cf']  = {number:98, amu:251, type:''};
chem.table['Es']  = {number:99, amu:252, type:''};
chem.table['Fm']  = {number:100, amu:257, type:''};
chem.table['Md']  = {number:101, amu:258, type:''};
chem.table['No']  = {number:102, amu:259, type:''};
chem.table['Lr']  = {number:103, amu:262, type:''};
chem.table['Rf']  = {number:104, amu:267, type:''};
chem.table['Db']  = {number:105, amu:268, type:''};
chem.table['Sg']  = {number:106, amu:271, type:''};
chem.table['Bh']  = {number:107, amu:272, type:''};
chem.table['Hs']  = {number:108, amu:270, type:''};
chem.table['Mt']  = {number:109, amu:276, type:''};
chem.table['Ds']  = {number:110, amu:281, type:''};
chem.table['Rg']  = {number:111, amu:280, type:''};
chem.table['Cn']  = {number:112, amu:285, type:''};
chem.table['Uut'] = {number:113, amu:284, type:''};
chem.table['Fl']  = {number:114, amu:289, type:''};
chem.table['Uup'] = {number:115, amu:288, type:''};
chem.table['Lv']  = {number:116, amu:293, type:''};
chem.table['Uus'] = {number:117, amu:294, type:''};
chem.table['Uuo'] = {number:118, amu:294, type:''};

chem.solve = function(input)
{
    var lower = input.toLowerCase();
    var upper = lower[0].toUpperCase() + lower.slice(1);

    var symbol = '';

    if (chem.names[lower])
    {
        symbol = chem.table[chem.names[lower]];

        return {header:upper, main:chem.names[lower] + '<br>Number ' + symbol.number + '<br>Amu ' + symbol.amu + '<br>Type ' + symbol.type, plain:input};
    }
    else if (chem.table[upper])
    {
        symbol = chem.table[upper];

        var name;

        for (var key in chem.names)
        {
            if (chem.names[key] === upper)
            {
                name = key[0].toUpperCase() + key.slice(1);
                break;
            }
        }

        return {header:upper, main:name + '<br>Number ' + symbol.number + '<br>Amu ' + symbol.amu + '<br>Type ' + symbol.type, plain:input};
    }
    
    return null;
};
